% Electric Source Imaging (ESI) from EEG using FieldTrip. Attention is
% focused on a couple Regions of Interest (ROI).
% Based on code by HXI for a similar, previous project.

%% CHANGELOG
% 2020-07-05
%    This file is a continuation of script_eeg_reconstruction.

%% ATLAS READING
%
% Brainnetome atlas is is recent (2016) and specific (123 subregions)
brainnetome = ft_read_atlas('BNA_MPM_thr25_1.25mm.nii');
brainnetome = ft_convert_coordsys(brainnetome,leadfield.coordsys);

% Regions Of Interest (ROI) were indicated by clinicians; equivalent areas
% within atlas were selected by EA
%
% dorsolateral prefrontal cortex (DL_PF_C)
DL_PF_C = ...
    {'SFG, Right Superior Frontal Gyrus A8dl, dorsolateral area 8',...
     'SFG, Left Superior Frontal Gyrus A8dl, dorsolateral area 8',...
     'SFG, Right Superior Frontal Gyrus A9l, lateral area 9',...
     'SFG, Left Superior Frontal Gyrus A9l, lateral area 9'};
% anterior cingulate cortex (A_C_C)
A_C_C = ...
    {'CG, Right Cingulate Gyrus A24rv, rostroventral area 24',...
     'CG, Left Cingulate Gyrus A24rv, rostroventral area 24',...
     'CG, Right Cingulate Gyrus A32p, pregenual area 32',...
     'CG, Left Cingulate Gyrus A32p, pregenual area 32',...
     'CG, Right Cingulate Gyrus A32sg, subgenual area 32',...
     'CG, Left Cingulate Gyrus A32sg, subgenual area 32'};
% insula (I)
I = ...
    {'INS, Right Insular Gyrus G, hypergranular insula',...
     'INS, Left Insular Gyrus G, hypergranular insula',...
     'INS, Right Insular Gyrus vIa, ventral agranular insula',...
     'INS, Left Insular Gyrus vIa, ventral agranular insula',...
     'INS, Right Insular Gyrus dIa, dorsal agranular insula',...
     'INS, Left Insular Gyrus dIa, dorsal agranular insula',...
     'INS, Right Insular Gyrus vId/vIg, ventral dysgranular and granular insula',...
     'INS, Left Insular Gyrus vId/vIg, ventral dysgranular and granular insula',...
     'INS, Right Insular Gyrus dIg, dorsal granular insula',...
     'INS, Left Insular Gyrus dIg, dorsal granular insula',...
     'INS, Right Insular Gyrus dId, dorsal dysgranular insula',...
     'INS, Left Insular Gyrus dId, dorsal dysgranular insula'};
% primary somatosensory cortex (P_SS_C)
P_SS_C = ...
    {'PoG, Right Postcentral Gyrus A1/2/3ulhf, area 1/2/3 (upper limb, head and face region)',...
     'PoG, Left Postcentral Gyrus A1/2/3ulhf, area 1/2/3 (upper limb, head and face region)',...
     'PoG, Right Postcentral Gyrus A1/2/3tonIa, area 1/2/3 (tongue and larynx region)',...
     'PoG, Left Postcentral Gyrus A1/2/3tonIa, area 1/2/3 (tongue and larynx region)',...
     'PoG, Right Postcentral Gyrus A2, area 2',...
     'PoG, Left Postcentral Gyrus A2, area 2',...
     'PoG, Right Postcentral Gyrus A1/2/3tru, area1/2/3 (trunk region)',...
     'PoG, Left Postcentral Gyrus A1/2/3tru, area1/2/3 (trunk region)'};
% ventroposterior lateral nucleus of thalamus (VPL_TH)
VPL_TH = ...
    {'Tha, Right Thalamus Stha, sensory thalamus',...
     'Tha, Left Thalamus Stha, sensory thalamus'};
% amygdala (A)
A = ...
    {'Amyg, Right Amygdala mAmyg, medial amygdala',...
     'Amyg, Left Amygdala mAmyg, medial amygdala',...
     'Amyg, Right Amygdala lAmyg, lateral amygdala',...
     'Amyg, Left Amygdala lAmyg, lateral amygdala'};
% periaquiductal gray
% nucleus raphe magnus
% -- last two not on atlas, TODO

%% PREPARATION OF ROI
%
% ROI are selected by combining regions of the atlas
% TODO: this is repetitive, must be automated
cfg = [];
cfg.atlas = brainnetome;

cfg.roi     = DL_PF_C;
DL_PF_C_msk = ft_volumelookup(cfg, leadfield);

cfg.roi     = A_C_C;
A_C_C_msk   = ft_volumelookup(cfg, leadfield);

cfg.roi     = I;
I_msk       = ft_volumelookup(cfg, leadfield);

cfg.roi     = P_SS_C;
P_SS_C_msk  = ft_volumelookup(cfg, leadfield);

cfg.roi     = VPL_TH;
VPL_TH_msk  = ft_volumelookup(cfg, leadfield);

cfg.roi     = A;
A_msk       = ft_volumelookup(cfg, leadfield);

% visual inspection
if false
figure()
ft_plot_mesh(vol.bnd(3), 'facecolor',[0.2 0.2 0.2], 'facealpha', 0.3,...
    'edgecolor', [1 1 1], 'edgealpha', 0.05);
title('Dorsolateral prefrontal cortex')
hold on;
scatter3(leadfield.pos(DL_PF_C_msk,1),...
         leadfield.pos(DL_PF_C_msk,2),...
         leadfield.pos(DL_PF_C_msk,3),'filled')
figure()
ft_plot_mesh(vol.bnd(3), 'facecolor',[0.2 0.2 0.2], 'facealpha', 0.3,...
    'edgecolor', [1 1 1], 'edgealpha', 0.05);
title('Anterior cingulate cortex')
hold on;
scatter3(leadfield.pos(A_C_C_msk,1),...
         leadfield.pos(A_C_C_msk,2),...
         leadfield.pos(A_C_C_msk,3),'filled')
figure()
title('Insula')
ft_plot_mesh(vol.bnd(3), 'facecolor',[0.2 0.2 0.2], 'facealpha', 0.3,...
    'edgecolor', [1 1 1], 'edgealpha', 0.05);
hold on;
scatter3(leadfield.pos(I_msk,1),...
         leadfield.pos(I_msk,2),...
         leadfield.pos(I_msk,3),'filled')
figure()
ft_plot_mesh(vol.bnd(3), 'facecolor',[0.2 0.2 0.2], 'facealpha', 0.3,...
    'edgecolor', [1 1 1], 'edgealpha', 0.05);
title('Primary somatosensory cortex')
hold on;
scatter3(leadfield.pos(P_SS_C_msk,1),...
         leadfield.pos(P_SS_C_msk,2),...
         leadfield.pos(P_SS_C_msk,3),'filled')
figure()
ft_plot_mesh(vol.bnd(3), 'facecolor',[0.2 0.2 0.2], 'facealpha', 0.3,...
    'edgecolor', [1 1 1], 'edgealpha', 0.05);
title('Ventroposterior lateral nucleus of thalamus')
hold on;
scatter3(leadfield.pos(VPL_TH_msk,1),...
         leadfield.pos(VPL_TH_msk,2),...
         leadfield.pos(VPL_TH_msk,3),'filled')
figure()
ft_plot_mesh(vol.bnd(3), 'facecolor',[0.2 0.2 0.2], 'facealpha', 0.3,...
    'edgecolor', [1 1 1], 'edgealpha', 0.05);
title('Amygdala')
hold on;
scatter3(leadfield.pos(A_msk,1),...
         leadfield.pos(A_msk,2),...
         leadfield.pos(A_msk,3),'filled')

% together
figure()
ft_plot_mesh(vol.bnd(3), 'facecolor',[0.2 0.2 0.2], 'facealpha', 0.3,...
    'edgecolor', [1 1 1], 'edgealpha', 0.05);
hold on;
scatter3(leadfield.pos(DL_PF_C_msk,1),...
         leadfield.pos(DL_PF_C_msk,2),...
         leadfield.pos(DL_PF_C_msk,3),'filled')
scatter3(leadfield.pos(A_C_C_msk,1),...
         leadfield.pos(A_C_C_msk,2),...
         leadfield.pos(A_C_C_msk,3),'filled')
scatter3(leadfield.pos(I_msk,1),...
         leadfield.pos(I_msk,2),...
         leadfield.pos(I_msk,3),'filled')
scatter3(leadfield.pos(P_SS_C_msk,1),...
         leadfield.pos(P_SS_C_msk,2),...
         leadfield.pos(P_SS_C_msk,3),'filled')
scatter3(leadfield.pos(VPL_TH_msk,1),...
         leadfield.pos(VPL_TH_msk,2),...
         leadfield.pos(VPL_TH_msk,3),'filled')
scatter3(leadfield.pos(A_msk,1),...
         leadfield.pos(A_msk,2),...
         leadfield.pos(A_msk,3),'filled')
end

%% DATA INSIDE ROI
%
% using ROI selection, source-data is selected
DL_PF_C_dat = sourceFC.avg.pow(DL_PF_C_msk,:);
A_C_C_dat   = sourceFC.avg.pow(A_C_C_msk,:);
I_dat       = sourceFC.avg.pow(I_msk,:);
P_SS_C_dat  = sourceFC.avg.pow(P_SS_C_msk,:);
VPL_TH_dat  = sourceFC.avg.pow(VPL_TH_msk,:);
A_dat       = sourceFC.avg.pow(A_msk,:);

% visual inspection
time = sourceFC.time;
figure()
plot(time,DL_PF_C_dat)
title('Dorsolateral prefrontal cortex')
figure()
plot(time,A_C_C_dat)
title('Anterior cingulate cortex')
figure()
plot(time,I_dat)
title('Insula')
figure()
plot(time,P_SS_C_dat)
title('Primary somatosensory cortex')
figure()
plot(time,VPL_TH_dat)
title('Ventroposterior lateral nucleus of thalamus')
figure()
plot(time,A_dat)
title('Amygdala')


%%
figure()
plot(time,DL_PF_C_dat(1:5,:))
title('Dorsolateral prefrontal cortex, first 5')


points = leadfield.pos(DL_PF_C_msk,:);
points = points(1:5,:);

figure()
ft_plot_mesh(vol.bnd(3), 'facecolor',[0.2 0.2 0.2], 'facealpha', 0.3,...
    'edgecolor', [1 1 1], 'edgealpha', 0.05);
title('Dorsolateral prefrontal cortex, first 5')
hold on;
scatter3(points(1,1),...
         points(1,2),...
         points(1,3),'filled')
scatter3(points(2,1),...
         points(2,2),...
         points(2,3),'filled')
scatter3(points(3,1),...
         points(3,2),...
         points(3,3),'filled')
scatter3(points(4,1),...
         points(4,2),...
         points(4,3),'filled')
scatter3(points(5,1),...
         points(5,2),...
         points(5,3),'filled')
     
     
% figure()
% plot(time,DL_PF_C_dat(3,:))
% title('Dorsolateral prefrontal cortex, first 1')
